#Trying to go to the faster container infrastructure of github
sudo: false

language: php

php:
  - 5.5
  #- 5.6 # included in the matrix below, which also sets the "cover" env var to "yes"
  - 7.0
  - hhvm
 
matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  include:
    - php: 5.5
      env: deps=low
    - php: 5.6
      env: cover=yes

env:
  global:
    - deps=no
    - cover=no

install:
  - if [ "$deps" = "no" ]; then composer $flag install; fi;
  - if [ "$deps" = "low" ]; then composer $flag --prefer-lowest --prefer-stable update; fi;

script:
  - mkdir -p build/logs
  - if [ "$cover" = "no" ]; then ./vendor/bin/phpunit ; fi;
  - if [ "$cover" = "yes" ]; then ./vendor/bin/phpunit --coverage-clover build/logs/coverage.xml ; fi;

before_install:
  - composer self-update
  - composer config --quiet github-oauth.github.com $GITHUB_TOKEN
  - if [[ ! $GITHUB_TOKEN ]]; then echo "no github token"; fi
  - if [[ ! $GITHUB_TOKEN ]]; then flag=--prefer-source; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --formatVersion=php-clover build/logs/coverage.xml
